<?php

/**
 * BaseFicheros
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $file
 * @property integer $versionid
 * @property string $descripcion
 * @property boolean $deleted
 * @property Version $Version
 * 
 * @method string   getNombre()      Returns the current record's "nombre" value
 * @method string   getFile()        Returns the current record's "file" value
 * @method integer  getVersionid()   Returns the current record's "versionid" value
 * @method string   getDescripcion() Returns the current record's "descripcion" value
 * @method boolean  getDeleted()     Returns the current record's "deleted" value
 * @method Version  getVersion()     Returns the current record's "Version" value
 * @method Ficheros setNombre()      Sets the current record's "nombre" value
 * @method Ficheros setFile()        Sets the current record's "file" value
 * @method Ficheros setVersionid()   Sets the current record's "versionid" value
 * @method Ficheros setDescripcion() Sets the current record's "descripcion" value
 * @method Ficheros setDeleted()     Sets the current record's "deleted" value
 * @method Ficheros setVersion()     Sets the current record's "Version" value
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFicheros extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ficheros');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('versionid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Version', array(
             'local' => 'versionid',
             'foreign' => 'id'));
    }
}