<?php

/**
 * BaseLineasVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $linea_base_id
 * @property integer $version_id
 * @property Version $Version
 * @property LineaBase $LineaBase
 * 
 * @method integer       getLineaBaseId()   Returns the current record's "linea_base_id" value
 * @method integer       getVersionId()     Returns the current record's "version_id" value
 * @method Version       getVersion()       Returns the current record's "Version" value
 * @method LineaBase     getLineaBase()     Returns the current record's "LineaBase" value
 * @method LineasVersion setLineaBaseId()   Sets the current record's "linea_base_id" value
 * @method LineasVersion setVersionId()     Sets the current record's "version_id" value
 * @method LineasVersion setVersion()       Sets the current record's "Version" value
 * @method LineasVersion setLineaBase()     Sets the current record's "LineaBase" value
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseLineasVersion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lineas_version');
        $this->hasColumn('linea_base_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('version_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Version', array(
             'local' => 'version_id',
             'foreign' => 'id'));

        $this->hasOne('LineaBase', array(
             'local' => 'linea_base_id',
             'foreign' => 'id'));
    }
}