<?php

/**
 * BaseLineaBase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property integer $proyecto_id
 * @property Proyecto $Proyecto
 * @property Doctrine_Collection $Versiones
 * @property Doctrine_Collection $LineasBases
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method integer             getProyectoId()  Returns the current record's "proyecto_id" value
 * @method Proyecto            getProyecto()    Returns the current record's "Proyecto" value
 * @method Doctrine_Collection getVersiones()   Returns the current record's "Versiones" collection
 * @method Doctrine_Collection getLineasBases() Returns the current record's "LineasBases" collection
 * @method LineaBase           setNombre()      Sets the current record's "nombre" value
 * @method LineaBase           setDescripcion() Sets the current record's "descripcion" value
 * @method LineaBase           setProyectoId()  Sets the current record's "proyecto_id" value
 * @method LineaBase           setProyecto()    Sets the current record's "Proyecto" value
 * @method LineaBase           setVersiones()   Sets the current record's "Versiones" collection
 * @method LineaBase           setLineasBases() Sets the current record's "LineasBases" collection
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseLineaBase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linea_base');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('proyecto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'proyecto_id',
             'foreign' => 'id'));

        $this->hasMany('Version as Versiones', array(
             'refClass' => 'LineasVersion',
             'local' => 'linea_base_id',
             'foreign' => 'version_id'));

        $this->hasMany('LineasVersion as LineasBases', array(
             'local' => 'id',
             'foreign' => 'linea_base_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $versionable0 = new Doctrine_Template_Versionable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}