<?php

/**
 * BaseTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $tipo
 * 
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getTipo()   Returns the current record's "tipo" collection
 * @method Tipo                setNombre() Sets the current record's "nombre" value
 * @method Tipo                setTipo()   Sets the current record's "tipo" collection
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Artefacto as tipo', array(
             'local' => 'id',
             'foreign' => 'tipo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}