<?php

/**
 * BaseAsignacionProyectos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $proyecto_Id
 * @property Proyecto $Proyecto
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getProyectoId()  Returns the current record's "proyecto_Id" value
 * @method Proyecto            getProyecto()    Returns the current record's "Proyecto" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method AsignacionProyectos setUserId()      Sets the current record's "user_id" value
 * @method AsignacionProyectos setProyectoId()  Sets the current record's "proyecto_Id" value
 * @method AsignacionProyectos setProyecto()    Sets the current record's "Proyecto" value
 * @method AsignacionProyectos setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAsignacionProyectos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asignacion_proyectos');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('proyecto_Id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'proyecto_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}