<?php

/**
 * BaseMensaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property boolean $leido
 * @property integer $user_id
 * @property sfGuardUser $sfGuardUser
 * 
 * @method string      getNombre()      Returns the current record's "nombre" value
 * @method string      getDescripcion() Returns the current record's "descripcion" value
 * @method boolean     getLeido()       Returns the current record's "leido" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Mensaje     setNombre()      Sets the current record's "nombre" value
 * @method Mensaje     setDescripcion() Sets the current record's "descripcion" value
 * @method Mensaje     setLeido()       Sets the current record's "leido" value
 * @method Mensaje     setUserId()      Sets the current record's "user_id" value
 * @method Mensaje     setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseMensaje extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensaje');
        $this->hasColumn('nombre', 'string', 300, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 300,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('leido', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}