<?php

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property string $fase
 * @property boolean $edicion
 * @property Doctrine_Collection $EstadosHijos
 * @property Doctrine_Collection $EstadosPadres
 * @property Doctrine_Collection $estado
 * 
 * @method string              getNombre()        Returns the current record's "nombre" value
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method string              getFase()          Returns the current record's "fase" value
 * @method boolean             getEdicion()       Returns the current record's "edicion" value
 * @method Doctrine_Collection getEstadosHijos()  Returns the current record's "EstadosHijos" collection
 * @method Doctrine_Collection getEstadosPadres() Returns the current record's "EstadosPadres" collection
 * @method Doctrine_Collection getEstado()        Returns the current record's "estado" collection
 * @method Estado              setNombre()        Sets the current record's "nombre" value
 * @method Estado              setDescripcion()   Sets the current record's "descripcion" value
 * @method Estado              setFase()          Sets the current record's "fase" value
 * @method Estado              setEdicion()       Sets the current record's "edicion" value
 * @method Estado              setEstadosHijos()  Sets the current record's "EstadosHijos" collection
 * @method Estado              setEstadosPadres() Sets the current record's "EstadosPadres" collection
 * @method Estado              setEstado()        Sets the current record's "estado" collection
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fase', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('edicion', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estado as EstadosHijos', array(
             'refClass' => 'EstadoHijo',
             'local' => 'padre_id',
             'foreign' => 'hijo_id'));

        $this->hasMany('EstadoHijo as EstadosPadres', array(
             'local' => 'id',
             'foreign' => 'padre_id'));

        $this->hasMany('Version as estado', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}