<?php

/**
 * BaseVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $identificador
 * @property string $descripcion
 * @property integer $tipo_id
 * @property integer $estado_id
 * @property integer $artefacto_id
 * @property boolean $validada
 * @property Estado $Estado
 * @property Tipo $Tipo
 * @property Artefacto $Artefacto
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Ficheros
 * @property Doctrine_Collection $LineasBase
 * @property Doctrine_Collection $LineasBases
 * @property Doctrine_Collection $AsignacionesTrabajo
 * 
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method integer             getIdentificador()       Returns the current record's "identificador" value
 * @method string              getDescripcion()         Returns the current record's "descripcion" value
 * @method integer             getTipoId()              Returns the current record's "tipo_id" value
 * @method integer             getEstadoId()            Returns the current record's "estado_id" value
 * @method integer             getArtefactoId()         Returns the current record's "artefacto_id" value
 * @method boolean             getValidada()            Returns the current record's "validada" value
 * @method Estado              getEstado()              Returns the current record's "Estado" value
 * @method Tipo                getTipo()                Returns the current record's "Tipo" value
 * @method Artefacto           getArtefacto()           Returns the current record's "Artefacto" value
 * @method Doctrine_Collection getUsers()               Returns the current record's "Users" collection
 * @method Doctrine_Collection getFicheros()            Returns the current record's "Ficheros" collection
 * @method Doctrine_Collection getLineasBase()          Returns the current record's "LineasBase" collection
 * @method Doctrine_Collection getLineasBases()         Returns the current record's "LineasBases" collection
 * @method Doctrine_Collection getAsignacionesTrabajo() Returns the current record's "AsignacionesTrabajo" collection
 * @method Version             setNombre()              Sets the current record's "nombre" value
 * @method Version             setIdentificador()       Sets the current record's "identificador" value
 * @method Version             setDescripcion()         Sets the current record's "descripcion" value
 * @method Version             setTipoId()              Sets the current record's "tipo_id" value
 * @method Version             setEstadoId()            Sets the current record's "estado_id" value
 * @method Version             setArtefactoId()         Sets the current record's "artefacto_id" value
 * @method Version             setValidada()            Sets the current record's "validada" value
 * @method Version             setEstado()              Sets the current record's "Estado" value
 * @method Version             setTipo()                Sets the current record's "Tipo" value
 * @method Version             setArtefacto()           Sets the current record's "Artefacto" value
 * @method Version             setUsers()               Sets the current record's "Users" collection
 * @method Version             setFicheros()            Sets the current record's "Ficheros" collection
 * @method Version             setLineasBase()          Sets the current record's "LineasBase" collection
 * @method Version             setLineasBases()         Sets the current record's "LineasBases" collection
 * @method Version             setAsignacionesTrabajo() Sets the current record's "AsignacionesTrabajo" collection
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseVersion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('version');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('identificador', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('tipo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('estado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('artefacto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('validada', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasOne('Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id'));

        $this->hasOne('Artefacto', array(
             'local' => 'artefacto_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'AsignacionTrabajadores',
             'local' => 'version_id',
             'foreign' => 'user_id'));

        $this->hasMany('Ficheros', array(
             'local' => 'id',
             'foreign' => 'versionid'));

        $this->hasMany('LineaBase as LineasBase', array(
             'refClass' => 'LineasVersion',
             'local' => 'version_id',
             'foreign' => 'linea_base_id'));

        $this->hasMany('LineasVersion as LineasBases', array(
             'local' => 'id',
             'foreign' => 'version_id'));

        $this->hasMany('AsignacionTrabajadores as AsignacionesTrabajo', array(
             'local' => 'id',
             'foreign' => 'version_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $versionable0 = new Doctrine_Template_Versionable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}