<?php

/**
 * BaseProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property string $url
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Asignaciones
 * @property Doctrine_Collection $proyecto
 * @property Doctrine_Collection $LineasBase
 * 
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getDescripcion()  Returns the current record's "descripcion" value
 * @method string              getUrl()          Returns the current record's "url" value
 * @method Doctrine_Collection getUsers()        Returns the current record's "Users" collection
 * @method Doctrine_Collection getAsignaciones() Returns the current record's "Asignaciones" collection
 * @method Doctrine_Collection getProyecto()     Returns the current record's "proyecto" collection
 * @method Doctrine_Collection getLineasBase()   Returns the current record's "LineasBase" collection
 * @method Proyecto            setNombre()       Sets the current record's "nombre" value
 * @method Proyecto            setDescripcion()  Sets the current record's "descripcion" value
 * @method Proyecto            setUrl()          Sets the current record's "url" value
 * @method Proyecto            setUsers()        Sets the current record's "Users" collection
 * @method Proyecto            setAsignaciones() Sets the current record's "Asignaciones" collection
 * @method Proyecto            setProyecto()     Sets the current record's "proyecto" collection
 * @method Proyecto            setLineasBase()   Sets the current record's "LineasBase" collection
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proyecto');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'AsignacionProyectos',
             'local' => 'proyecto_id',
             'foreign' => 'user_id'));

        $this->hasMany('AsignacionProyectos as Asignaciones', array(
             'local' => 'id',
             'foreign' => 'proyecto_id'));

        $this->hasMany('Artefacto as proyecto', array(
             'local' => 'id',
             'foreign' => 'proyecto_id'));

        $this->hasMany('LineaBase as LineasBase', array(
             'local' => 'id',
             'foreign' => 'proyecto_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}