<?php

/**
 * BaseFicherosArt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $file
 * @property integer $artefactoid
 * @property string $descripcion
 * @property boolean $deleted
 * @property Artefacto $Artefacto
 * 
 * @method string      getNombre()      Returns the current record's "nombre" value
 * @method string      getFile()        Returns the current record's "file" value
 * @method integer     getArtefactoid() Returns the current record's "artefactoid" value
 * @method string      getDescripcion() Returns the current record's "descripcion" value
 * @method boolean     getDeleted()     Returns the current record's "deleted" value
 * @method Artefacto   getArtefacto()   Returns the current record's "Artefacto" value
 * @method FicherosArt setNombre()      Sets the current record's "nombre" value
 * @method FicherosArt setFile()        Sets the current record's "file" value
 * @method FicherosArt setArtefactoid() Sets the current record's "artefactoid" value
 * @method FicherosArt setDescripcion() Sets the current record's "descripcion" value
 * @method FicherosArt setDeleted()     Sets the current record's "deleted" value
 * @method FicherosArt setArtefacto()   Sets the current record's "Artefacto" value
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFicherosArt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ficherosArt');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('artefactoid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artefacto', array(
             'local' => 'artefactoid',
             'foreign' => 'id'));
    }
}