<?php

/**
 * BaseEstadoHijo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $padre_id
 * @property integer $hijo_id
 * @property string $mensaje
 * @property Estado $EstadosHijos
 * @property Estado $EstadosPadres
 * 
 * @method integer    getPadreId()       Returns the current record's "padre_id" value
 * @method integer    getHijoId()        Returns the current record's "hijo_id" value
 * @method string     getMensaje()       Returns the current record's "mensaje" value
 * @method Estado     getEstadosHijos()  Returns the current record's "EstadosHijos" value
 * @method Estado     getEstadosPadres() Returns the current record's "EstadosPadres" value
 * @method EstadoHijo setPadreId()       Sets the current record's "padre_id" value
 * @method EstadoHijo setHijoId()        Sets the current record's "hijo_id" value
 * @method EstadoHijo setMensaje()       Sets the current record's "mensaje" value
 * @method EstadoHijo setEstadosHijos()  Sets the current record's "EstadosHijos" value
 * @method EstadoHijo setEstadosPadres() Sets the current record's "EstadosPadres" value
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseEstadoHijo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_hijo');
        $this->hasColumn('padre_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('hijo_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('mensaje', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado as EstadosHijos', array(
             'local' => 'padre_id',
             'foreign' => 'id'));

        $this->hasOne('Estado as EstadosPadres', array(
             'local' => 'hijo_Id',
             'foreign' => 'id'));
    }
}