<?php

/**
 * BaseAsignacionTrabajadoresArt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $artefacto_id
 * @property Artefacto $Artefacto
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer                   getUserId()       Returns the current record's "user_id" value
 * @method integer                   getArtefactoId()  Returns the current record's "artefacto_id" value
 * @method Artefacto                 getArtefacto()    Returns the current record's "Artefacto" value
 * @method sfGuardUser               getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method AsignacionTrabajadoresArt setUserId()       Sets the current record's "user_id" value
 * @method AsignacionTrabajadoresArt setArtefactoId()  Sets the current record's "artefacto_id" value
 * @method AsignacionTrabajadoresArt setArtefacto()    Sets the current record's "Artefacto" value
 * @method AsignacionTrabajadoresArt setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAsignacionTrabajadoresArt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asignacion_trabajadores_art');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('artefacto_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artefacto', array(
             'local' => 'artefacto_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}