<?php

/**
 * ArtefactoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtefactoTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object ArtefactoTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Artefacto');
	}

	public function buscarArtefactos($proyectoId,Doctrine_Query $q = null) {
		$q = Doctrine_Query::create()->from('Artefacto a');
		$q->andWhere('a.proyecto_id = ?', $proyectoId);
		return $q;
	}

	public function artefactosValidados(Doctrine_Query $q = null) {
		$q->andWhere('a.validado = ?', true);
		return $q;
	}
}