<?php

/**
 * AsignacionProyectosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignacionProyectosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignacionProyectosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignacionProyectos');
    }
}