<?php

/**
 * AsignacionTrabajadoresArtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignacionTrabajadoresArtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignacionTrabajadoresArtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignacionTrabajadoresArt');
    }
}