<?php

/**
 * EstadoHijoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoHijoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoHijoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoHijo');
    }
}