<?php

/**
 * FicherosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicherosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FicherosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ficheros');
    }
}