<?php

/**
 * LineasVersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LineasVersionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LineasVersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LineasVersion');
    }
}