<?php

/**
 * LineaBaseTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LineaBaseTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object LineaBaseTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('LineaBase');
	}

	public function buscarLineasBase($proyectoId,Doctrine_Query $q = null) {
		$q = Doctrine_Query::create()->from('LineaBase a');
		$q->andWhere('a.proyecto_id = ?', $proyectoId);
		return $q;
	}
}