<?php

/**
 * RelacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Relaciones');
    }
}