<?php

/**
 * Version
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gestor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Version extends BaseVersion
{
	public function tramitable() {
		return sfContext::getInstance()->getUser()->hasPermission($this->getEstado()->getNombre());
		//		return (in_array($this->getEstado(), sfContext::getInstance()->getUser()->cargarPermisos()));
	}

	public static function tramitableEstado($estado) {
		return sfContext::getInstance()->getUser()->hasPermission($estado);
		//		return (in_array($this->getEstado(), sfContext::getInstance()->getUser()->cargarPermisos()));
	}


}